[package]
authors = ["worstpractice <54796463+worstpractice@users.noreply.github.com>"]
edition = "2018"
name    = "babbys_first_thread_pool"
version = "0.1.0"

[dependencies]
chrono      = "0.4.19"
lazy_static = "1.4.0"
num_cpus    = "1.13.0"
