[package]
name = "babbys_first_thread_pool"
version = "0.1.0"
authors = ["worstpractice <54796463+worstpractice@users.noreply.github.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"
chrono = "0.4.15"
